### PR TITLE
Allow jabber:client and jabber:component:accept to appear

### PR DESCRIPTION
**Pull request by singpolyma**
With forwarded stanzas (especially for carbons and mam) these may appear more deeply nested and we can't just remove them.

### CODE REVIEW

**Comment by bklang** [comment]
Hm, thanks. No particular objection to your justification, but I don't know why we originally had the functionality to exclude those namespaces, and it looks like a decision from the maintainers before us. I'm also surprised this doesn't break any specs. 

@singpolyma do you know why this might have been excluded in the first place?

**Comment by singpolyma** [comment]
I expect it was excluded to make having the two namespaces with the same element names (one for clients and one for components) easier to deal with in some places.  but it's not too hard to just check for them both and without them carbons and MAM are almost impossible to implement correctly.

**Comment by bklang** [comment]
Thanks for that explanation. I prefer correct behavior over convenient behavior, so this makes sense to me.

Do you think this change could affect any Blather clients in the wild? A changelog entry (or some other upgrade note in the README) would be helpful.

**Comment by singpolyma** [comment]
Very unlikely anyone would be affected, since only subject/body/thread are affected inside of stanzas.  But I have added a changelog entry for maximum safety.

**Pull request merged**
