### PR TITLE
Unlock Nokogiri to allow >=1.8.3 now that issues are fixed upstream

### PR DESCRIPTION
**Pull request by chewi**
Yes! Finally! Please let's get a new release out as this addresses some very important security vulnerabilities.

### CODE REVIEW

**Comment by lpradovera** [comment]
Yay! About time :)

**Comment by chewi** [comment]
Actually just noticed the workaround I put in earlier, shouldn't need that now. Hold on...

**Comment by chewi** [comment]
Scratch that, there hasn't been a new JRuby-OpenSSL release yet. Let's go!

**Comment by chewi** [comment]
Obviously Blather itself hasn't really changed though I understand behavioural changes could still arise from this. I haven't noticed any though.

**Comment by benlangfeld** [comment]
Released.

**Comment by chewi** [comment]
Now for ruby_speech...

**Pull request merged**
