### PR TITLE
Remove dependency on sucker_punch

### PR DESCRIPTION
**Pull request by singpolyma**
Since EM has a built-in worker pool for those who need it.

### CODE REVIEW

**Comment by bklang** [comment]
Thanks for this contribution! It makes sense, though it would be a breaking change. If you want to start thinking about what could go into a Blather 3 release, this would be a good candidate.

**Comment by singpolyma** [comment]
I'm curious in what way this is a breaking change.  I intentionally kept the API and behaviour the same.  If we want to start a 3.x branch and put this there instead that's fine with me, but I might rework the API a bit to no longer use the worker count thing.

**Comment by bklang** [comment]
It's the removal of the class and its methods that represents a breaking change. For example, any Blather application which directly interacts with `Blather::Client::Job#perform` would break after this change.

**Comment by singpolyma** [comment]
Oh interesting, was that considered part of the public API?  Ok.  If you make a v3 branch I'll make tweak the PR a bit and target that

**Comment by bklang** [comment]
It wasn't exactly advertised, but neither was it marked as private or internal. I'd rather err on the side of caution rather than giving someone an unexpected surprise.

If you're ready to start making other changes, we can consider the `develop` branch to be the future v3, and make support releases off the current `master` branch for v2 fixes (if any).  So thee only thing I'd ask for at this point is a note in the changelog and readme indicating that the develop branch now contains breaking changes relative to v2.

**Comment by singpolyma** [comment]
@bklang updated

**Review by bklang — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
