### PR TITLE
Switch from EventMachine to Celluloid

### PR DESCRIPTION
**Pull request by benlangfeld**
WIP. Still need to deal with:
- [ ] TLS
- [ ] SOCKS5 file transfers

### CODE REVIEW

**Comment by alakra** [comment]
Is this still a goal for the project?

**Comment by benlangfeld** [comment]
Absolutely @alakra, but unfortunately I've not had time to work on the two pending issues.

**Comment by chewi** [comment]
Blather with EventMachine 1.2 causes a segfault. Time to switch?

**Comment by singpolyma** [comment]
I vote this be closed.  If we want to leave EM someday, the way forward is FiberScheduler / Async these days.

**Pull request closed without merging**
